import type { Roastery } from './types';
import { v4 as uuidv4 } from 'uuid';

// Note: Using uuidv4() here means IDs will be different on every server restart
// or build. In a real-world scenario with a persistent database, these would be stable.
// For our localStorage-based app, this is acceptable as the static list is a starting point.

export const israeliRoasteries: Roastery[] = [
  { id: uuidv4(), name: "Abyssinia", isFromStaticList: true },
  { id: uuidv4(), name: "AGA", isFromStaticList: true },
  { id: uuidv4(), name: "Air Roastery", isFromStaticList: true },
  { id: uuidv4(), name: "Beanz", isFromStaticList: true },
  { id: uuidv4(), name: "Cafelix", isFromStaticList: true },
  { id: uuidv4(), name: "Caffe's", isFromStaticList: true },
  { id: uuidv4(), name: "Coffee Lab", isFromStaticList: true },
  { id: uuidv4(), name: "Coffee Station", isFromStaticList: true },
  { id: uuidv4(), name: "CoffeeShop", isFromStaticList: true },
  { id: uuidv4(), name: "Columbus", isFromStaticList: true },
  { id: uuidv4(), name: "DADA", isFromStaticList: true },
  { id: uuidv4(), name: "Edmond's", isFromStaticList: true },
  { id: uuidv4(), name: "Einat's Coffee", isFromStaticList: true },
  { id: uuidv4(), name: "Fazza", isFromStaticList: true },
  { id: uuidv4(), name: "Gili's Coffee", isFromStaticList: true },
  { id: uuidv4(), name: "HOC - House of Coffee", isFromStaticList: true },
  { id: uuidv4(), name: "Jera", isFromStaticList: true },
  { id: uuidv4(), name: "Kivun", isFromStaticList: true },
  { id: uuidv4(), name: "Kurto's", isFromStaticList: true },
  { id: uuidv4(), name: "Legacy", isFromStaticList: true },
  { id: uuidv4(), name: "Mae", isFromStaticList: true },
  { id: uuidv4(), name: "Mishmash", isFromStaticList: true },
  { id: uuidv4(), name: "Moka", isFromStaticList: true },
  { id: uuidv4(), name: "MOR", isFromStaticList: true },
  { id: uuidv4(), name: "Nahat", isFromStaticList: true },
  { id: uuidv4(), name: "Ofer Coffee", isFromStaticList: true },
  { id: uuidv4(), name: "Origo", isFromStaticList: true },
  { id: uuidv4(), name: "Power Coffee", isFromStaticList: true },
  { id: uuidv4(), name: "Rosso", isFromStaticList: true },
  { id: uuidv4(), name: "Shraga", isFromStaticList: true },
  { id: uuidv4(), name: "Story Espresso", isFromStaticList: true },
  { id: uuidv4(), name: "The Coffee Roasting House", isFromStaticList: true },
  { id: uuidv4(), name: "Torrefazione", isFromStaticList: true },
  { id: uuidv4(), name: "TOAST", isFromStaticList: true },
  { id: uuidv4(), name: "Uchtopus", isFromStaticList: true },
  { id: uuidv4(), name: "Veronia", isFromStaticList: true },
  { id: uuidv4(), name: "WayCup", isFromStaticList: true },
  { id: uuidv4(), name: "We Love Coffee", isFromStaticList: true },
  { id: uuidv4(), name: "Whiteroo", isFromStaticList: true },
  { id: uuidv4(), name: "WiseCup", isFromStaticList: true },
  { id: uuidv4(), name: "Zaza", isFromStaticList: true },
  { id: uuidv4(), name: "Zunto", isFromStaticList: true },
].sort((a, b) => a.name.localeCompare(b.name));
